version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: &volume
      - ./:/app
    command: ["nodemon", "--exec", "python3", "main.py"]
  notebook:
    build:
      context: .
      dockerfile: Dockerfile-notebook
    command: ["jupyter", "notebook", "--no-browser"]
    ports:
      - "8888:8888"
    volumes: *volume
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
